version: "3"
services:
  client:
    environment:
      - NODE_ENV=local
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: client.dockerfile
  api:
    ports:
      - "3001:3001"
    build:
      context: .
      dockerfile: api.dockerfile
    healthcheck:
      test: "curl --fail http://localhost:3000/api/metadata"
      interval: 30s
      timeout: 5s
      retries: 3
