version: "3"
services:
  client:
    environment:
      - NODE_ENV=local
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: client.dockerfile
    volumes:
    - "./client:/usr/src/web/client"
    - "./routes:/usr/src/web/routes"
    - "./tools:/usr/src/web/tools"
    - "./build:/usr/src/web/build"
    - "./api:/usr/src/web/api"
  api:
    ports:
      - "3001:3001"
    build:
      context: .
      dockerfile: api.dockerfile
    volumes:
    - "./api:/usr/src/api/api"
    - "./routes:/usr/src/api/routes"
    - "./tools:/usr/src/api/tools"
    - "./build:/usr/src/api/build"
    healthcheck:
      test: "curl --fail http://localhost:3000/api/metadata"
      interval: 30s
      timeout: 5s
      retries: 3
