version: "3"
services:
  client:
    environment:
      - NODE_ENV=local
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: client.dockerfile
    volumes:
    - "${PWD}/client:/usr/src/web/client"
    - "${PWD}/routes:/usr/src/web/routes"
    - "${PWD}/tools:/usr/src/web/tools"
    - "${PWD}/build:/usr/src/web/build"
    - "${PWD}/api:/usr/src/web/api"
    - "${PWD}/.env:/usr/src/web/.env"
    - "${PWD}/pulpfile.mjs:/usr/src/web/pulpfile.mjs"
    - "${PWD}/webpack.common.mjs:/usr/src/web/webpack.common.mjs"
    - "${PWD}/webpack.dev.mjs:/usr/src/web/webpack.dev.mjs"
    - "${PWD}/webpack.prod.mjs:/usr/src/web/webpack.prod.mjs"
    - "${PWD}/package.json:/usr/src/web/package.json"
    - "${PWD}/package-lock.json:/usr/src/web/package-lock.json"
  api:
    ports:
      - "3001:3001"
    build:
      context: .
      dockerfile: api.dockerfile
    volumes:
    - "${PWD}/client:/usr/src/api/client"
    - "${PWD}/api:/usr/src/api/api"
    - "${PWD}/routes:/usr/src/api/routes"
    - "${PWD}/tools:/usr/src/api/tools"
    - "${PWD}/build:/usr/src/api/build"
    - "${PWD}/.env:/usr/src/api/.env"
    - "${PWD}/pulpfile.mjs:/usr/src/api/pulpfile.mjs"
    - "${PWD}/webpack.common.mjs:/usr/src/api/webpack.common.mjs"
    - "${PWD}/webpack.dev.mjs:/usr/src/api/webpack.dev.mjs"
    - "${PWD}/webpack.prod.mjs:/usr/src/api/webpack.prod.mjs"
    - "${PWD}/package.json:/usr/src/api/package.json"
    - "${PWD}/package-lock.json:/usr/src/api/package-lock.json"

    healthcheck:
      test: "curl --fail http://localhost:3000/api/metadata"
      interval: 30s
      timeout: 5s
      retries: 3
