name: Continuous Integration
on: push
jobs:
  build:
    name: Audits
    runs-on: ubuntu-latest
    steps:
      - uses: jakejarvis/lighthouse-action@v0.1.0
        url: 'http://mood.rgrannell2.now.sh/'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
